all:
	g++ -std=c++11 -fPIC test.cpp -o test -I. -I/workspace1/ckp/dlib-19.7 -I/usr/include -I/usr/include/opencv -I/usr/include/opencv2 `pkg-config --libs opencv` -lembed -L/workspace1/ckp/mclab_test/lib 
