all:
	g++ -std=c++11 main.cpp -o test -I. /workspace1/ckp/mclab_test/lib/embed_face_feature.pic.o -I/usr/include -I/usr/include/opencv -I/usr/include/opencv2 `pkg-config --libs opencv` -lembed_face_feature -L/workspace1/ckp/mclab_test/lib
